payment filter: improve payment filter technology
PAYONE-GmbH/shopware-6 pull request #225
Opened 2022-11-21 21:46 UTC by rommelfreddy

+ make it more abstract
+ make it more usable for other payment methods
+ make it more extensible

2022-11-22 11:03 UTC, momocode-de requested changes

2022-11-22 11:03 UTC, momocode-de commented on tests/Components/PaymentFilter/DefaultPaymentFilterServiceTest.php
> +
Bitte noch die `@covers` Annotation einbauen

2022-11-22 11:03 UTC, momocode-de commented on tests/Components/PaymentFilter/KlarnaPaymentFilterTest.php
> +
Bitte noch die `@covers` Annotation einbauen

2022-11-22 11:03 UTC, momocode-de commented on tests/Components/PaymentFilter/Przelewy24PaymentFilterTest.php
> +
Bitte noch die `@covers` Annotation einbauen

2022-12-02 12:44 UTC, rommelfreddy commented on tests/Components/PaymentFilter/Przelewy24PaymentFilterTest.php
> +
done.

2022-12-02 12:44 UTC, rommelfreddy commented on tests/Components/PaymentFilter/DefaultPaymentFilterServiceTest.php
> +
done.

2022-12-02 12:44 UTC, rommelfreddy commented on tests/Components/PaymentFilter/Przelewy24PaymentFilterTest.php
> +
done.

2022-12-05 07:23 UTC, momocode-de approved these changes

2023-01-03 08:40 UTC, merged