PAYOSWXP-25: integrate postfinance
PAYONE-GmbH/shopware-6 pull request #227
Opened 2022-11-21 21:49 UTC by rommelfreddy

depends on PR
- https://github.com/PAYONE-GmbH/shopware-6/pull/225
- https://github.com/PAYONE-GmbH/shopware-6/pull/226

2022-11-22 11:17 UTC, momocode-de requested changes

2022-11-22 11:17 UTC, momocode-de commented on tests/Components/PaymentFilter/PostfinancePaymentFilterTest.php
> +
Bitte noch die `@covers` Annotation ergänzen

2022-11-22 11:17 UTC, momocode-de commented on tests/PaymentHandler/PayonePostfinanceCardPaymentHandlerTest.php
> +
Bitte noch die `@covers` Annotation ergänzen

2022-11-22 11:17 UTC, momocode-de commented on tests/PaymentHandler/PayonePostfinanceWalletPaymentHandlerTest.php
> +
Bitte noch die `@covers` Annotation ergänzen

2022-12-02 12:42 UTC, rommelfreddy commented on tests/PaymentHandler/PayonePostfinanceWalletPaymentHandlerTest.php
> +
done.

2022-12-02 12:42 UTC, rommelfreddy commented on tests/PaymentHandler/PayonePostfinanceCardPaymentHandlerTest.php
> +
done.

2022-12-02 12:42 UTC, rommelfreddy commented on tests/Components/PaymentFilter/PostfinancePaymentFilterTest.php
> +
done.

2023-01-11 17:52 UTC, momocode-de approved these changes

2023-01-12 08:11 UTC, merged